configure the IP and hostname on both VMs 

2. Create playbook in GitHub ensure extension is .yml and commit the changes

3. sync project 

4. create inventory 
	create two host for both VMs 

5. Credentials using Machine type root/root

6. Create template and run the template. 

7. ensure the tasks executed, it applied 


---
- name: Install application
  hosts: all
  become: true

  tasks:
    - name: Install Apache
      ansible.builtin.dnf:
        name: httpd
        state: present

    - name: Start Apache
      ansible.builtin.systemd:
        name: httpd
        state: started
        enabled: true



